#include<iostream.h>
#include<conio.h>

void HOME()
{
   textcolor(4);
   cprintf("                 /\\               |--------------|               /\\");   cprintf("\r\n");
   cprintf("               /    \\             |                            /    \\ ");   cprintf("\r\n");
   cprintf("             /        \\           |                          /        \\");   cprintf("\r\n");
   cprintf("           /            \\         |--------------|         /            \\");   cprintf("\r\n");
   cprintf("         /----------------\\                      |       /----------------\\");   cprintf("\r\n");
   cprintf("       /                    \\                    |     /                    \\ ");   cprintf("\r\n");
   cprintf("     /                        \\ . |--------------| . /                        \\");   cprintf("\r\n\n");
   textcolor(1);
   cprintf("  |---------| |       | ---|--- |------| \\     / /-----\\   |-------| |-------\\ ");   cprintf("\r\n")  ;
   cprintf("  |           |       |    |    |      |  \\   / |       |  |       | |       |");   cprintf("\r\n")  ;
   cprintf("  |           |       |    |    |      |   \\ /  |       |  |       | |       | ");   cprintf("\r\n")  ;
   cprintf("  |---------| |-------|    |    |------|    |   |-------|  |-------| |       | ");   cprintf("\r\n")  ;
   cprintf("            | |       |    |    |           |   |       |  |\\        |       |");   cprintf("\r\n")  ;
   cprintf("            | |       |    |    |           |   |       |  |  \\      |       | " );   cprintf("\r\n")  ;
   cprintf("  |---------| |       | ---|--- |           |   |       |  |    \\    |-------/");   cprintf("\r\n\n")  ;
   textcolor(7);
}